include: 
    project: docker/template
    file: debian-pkg-ng.yaml
variables:
    package_name: "zulu-linux-image"
    build_exactly_for: "stable-zulu" # omit neuron64 for now
    build_for_product: "zulu"
    GIT_SUBMODULE_STRATEGY: none
