# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_MXC) += unipi-zulu.dtb \
			  unipi-patron.dtb \
			  unipi-acheating.dtb \
			  unipi-zulu-test.dtb \
			  unipi-zulu-gpiotest.dtb \
			  unipi-patron-finaltest.dtb \
			  unipi-zulu-altboot.dtb \
			  unipi-iris-finaltest.dtb

DTC_FLAGS_unipi-iris := -@
DTC_FLAGS_unipi-patron := -@

dtb-$(CONFIG_ARCH_MXC) += unipi-iris.dtb
