# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_MXC) += unipi-zulu.dtb \
			  unipi-patron.dtb \
			  unipi-zulu-test.dtb \
			  unipi-zulu-gpiotest.dtb \
			  unipi-patron-finaltest.dtb

DTC_FLAGS_unipi-gpro01 := -@
DTC_FLAGS_unipi-gpro01-iqrf-slot1 := -@
DTC_FLAGS_unipi-gpro01-iqrf-slota := -@
DTC_FLAGS_unipi-iris := -@
DTC_FLAGS_unipi-iris-unispi-slot1 := -@
DTC_FLAGS_unipi-iris-unispi-slota := -@

dtb-$(CONFIG_ARCH_MXC) += unipi-gpro01.dtb
dtb-$(CONFIG_ARCH_MXC) += unipi-gpro01-iqrf-slot1.dtb
dtb-$(CONFIG_ARCH_MXC) += unipi-gpro01-iqrf-slota.dtb

dtb-$(CONFIG_ARCH_MXC) += unipi-iris.dtb
dtb-$(CONFIG_ARCH_MXC) += unipi-iris-unispi-slot1.dtb
dtb-$(CONFIG_ARCH_MXC) += unipi-iris-unispi-slota.dtb
